# Generated by Django 4.2.20 on 2025-05-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sq_ft', models.IntegerField()),
                ('water_filter', models.BooleanField(default=False)),
                ('water_filter_replace', models.DateField()),
                ('fireplace', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cottage')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='cottage',
            name='clean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clean_cottages', to='home.reservation'),
        ),
    ]
