# Generated by Django 4.2.20 on 2025-05-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cottage_reservation_delete_post_cottage_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='fireplace',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='water_filter',
            field=models.IntegerField(default=False),
        ),
    ]
