# Generated by Django 4.2.20 on 2025-05-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cottage_fireplace_alter_cottage_water_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottage',
            old_name='clean',
            new_name='clean_date',
        ),
    ]
