# Generated by Django 4.2.20 on 2025-05-03 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_rename_clean_cottage_clean_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='id',
        ),
        migrations.AddField(
            model_name='cottage',
            name='cottage_id',
            field=models.CharField(default='A', max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='clean_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clean_date', to='home.reservation'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='fireplace',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='water_filter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='water_filter_replace',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved', to='home.cottage'),
        ),
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cottage_completed', to='home.cottage')),
                ('discount', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complete_discount', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_completed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
