# Generated by Django 4.2.20 on 2025-05-03 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_cottage_id_cottage_cottage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('bank', models.IntegerField()),
                ('credit_card', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='complete',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complete',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complete',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_completed', to='home.guest'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserver', to='home.guest'),
        ),
    ]
