# Generated by Django 4.2.20 on 2025-05-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_guest_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='bank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='credit_card',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
