# Generated by Django 4.2.20 on 2025-05-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_guest_bank_alter_guest_credit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='clean_date',
        ),
    ]
