# Generated by Django 4.2.20 on 2025-05-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_cottage_clean_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='res_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
