# Generated by Django 4.2.20 on 2025-05-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20250503_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
