# Generated by Django 4.2.20 on 2025-05-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_reservation_id_alter_reservation_res_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='res_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserver', to='home.guest'),
        ),
        migrations.AlterField(
            model_name='complete',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_reservations', to='home.guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='home.guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
