# Generated by Django 4.2.20 on 2025-05-03 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_complete_res_id_alter_complete_guest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='res_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserver', to='home.reservation'),
        ),
    ]
