# Generated by Django 4.2.20 on 2025-05-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_reservation_is_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
    ]
