# Generated by Django 4.2.20 on 2025-05-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_complete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complete',
            name='note',
        ),
    ]
