# Generated by Django 4.2.20 on 2025-05-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_complete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_note', to='home.reservation'),
        ),
    ]
