# Generated by Django 4.2.20 on 2025-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_complete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
