# Generated by Django 4.2.20 on 2025-05-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_complete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='note',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
